on:
  push:
    tags:
      - "*"

name: Create Release

jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: write
      
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          mvn -B versions:set -DnewVersion=${{github.ref_name}}
          mvn -B package
      - name: Upload release binary
        uses: alexellis/upload-assets@0.3.0
        env:
            GITHUB_TOKEN: ${{ github.token }}
        with:
            asset_paths: '["target/*.jar"]'
